// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gnozzle.proto

/*
Package gnozzle is a generated protocol buffer package.

It is generated from these files:
	gnozzle.proto

It has these top-level messages:
	LogRequest
	LogResponse
*/
package gnozzle

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LogRequest struct {
	Token          string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Appname        string `protobuf:"bytes,2,opt,name=appname" json:"appname,omitempty"`
	SubscriptionId string `protobuf:"bytes,3,opt,name=subscriptionId" json:"subscriptionId,omitempty"`
}

func (m *LogRequest) Reset()                    { *m = LogRequest{} }
func (m *LogRequest) String() string            { return proto.CompactTextString(m) }
func (*LogRequest) ProtoMessage()               {}
func (*LogRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LogRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LogRequest) GetAppname() string {
	if m != nil {
		return m.Appname
	}
	return ""
}

func (m *LogRequest) GetSubscriptionId() string {
	if m != nil {
		return m.SubscriptionId
	}
	return ""
}

type LogResponse struct {
	Output string `protobuf:"bytes,1,opt,name=output" json:"output,omitempty"`
}

func (m *LogResponse) Reset()                    { *m = LogResponse{} }
func (m *LogResponse) String() string            { return proto.CompactTextString(m) }
func (*LogResponse) ProtoMessage()               {}
func (*LogResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LogResponse) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func init() {
	proto.RegisterType((*LogRequest)(nil), "LogRequest")
	proto.RegisterType((*LogResponse)(nil), "LogResponse")
}

func init() { proto.RegisterFile("gnozzle.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xcf, 0xcb, 0xaf,
	0xaa, 0xca, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x4a, 0xe1, 0xe2, 0xf2, 0xc9, 0x4f,
	0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe1, 0x62, 0x2d, 0xc9, 0xcf, 0x4e, 0xcd,
	0x93, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x84, 0x24, 0xb8, 0xd8, 0x13, 0x0b, 0x0a,
	0xf2, 0x12, 0x73, 0x53, 0x25, 0x98, 0xc0, 0xe2, 0x30, 0xae, 0x90, 0x1a, 0x17, 0x5f, 0x71, 0x69,
	0x52, 0x71, 0x72, 0x51, 0x66, 0x41, 0x49, 0x66, 0x7e, 0x9e, 0x67, 0x8a, 0x04, 0x33, 0x58, 0x01,
	0x9a, 0xa8, 0x92, 0x2a, 0x17, 0x37, 0xd8, 0x96, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x31,
	0x2e, 0xb6, 0xfc, 0xd2, 0x92, 0x82, 0xd2, 0x12, 0xa8, 0x3d, 0x50, 0x9e, 0x91, 0x09, 0xd8, 0x31,
	0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0x20, 0xc3, 0xd9, 0x1d, 0x0b, 0x0a, 0x7c, 0xf2, 0xd3, 0x8b,
	0x85, 0xb8, 0xf5, 0x10, 0x8e, 0x94, 0xe2, 0xd1, 0x43, 0x32, 0x4b, 0x89, 0x21, 0x89, 0x0d, 0xec,
	0x13, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xab, 0x02, 0xe1, 0x9e, 0xda, 0x00, 0x00, 0x00,
}
